name: Trigger auto deployment for lobby

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/lobby-AutoDeployTrigger-e0e15281-bae2-44d4-be76-c8dfef277881.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  package:
    if: github.repository == 'throneteki/throneteki' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source and submodules
      uses: actions/checkout@v3
      with:
         fetch-depth: '0'
         submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.14
      with:
        versionSpec: 5.x
    - id: determine_version
      name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.14
      with:
        additionalArguments: /overrideconfig mode=Mainline
    - name: Build and push lobby
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cryogen/throneteki-lobby:latest, cryogen/throneteki-lobby:${{ steps.determine_version.outputs.semVer }}   
    - name: Build and push node
      uses: docker/build-push-action@v3
      with:
        push: true
        file: server/gamenode/Dockerfile
        tags: cryogen/throneteki-node:latest, cryogen/throneteki-node:${{ steps.determine_version.outputs.semVer }} 

     

